-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 23-11-2022 a las 12:10:16
-- Versión del servidor: 10.4.21-MariaDB
-- Versión de PHP: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `recetario`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `carne`
--

CREATE TABLE `carne` (
  `Nombre` varchar(45) NOT NULL,
  `Ingredientes` text NOT NULL,
  `Descripcion` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `carne`
--

INSERT INTO `carne` (`Nombre`, `Ingredientes`, `Descripcion`) VALUES
('Albondigas ', 'Para las albóndigas<br>\r\n500 g de carne picada de ternera <br>\r\n500 g de carne picada de cerdo <br>\r\nHarina <br>\r\n2 dientes de ajo <br>\r\n1 rebanada de pan <br>\r\nUn chorrito de leche <br>\r\nPerejil <br>\r\nUnos granos de pimienta negra <br>\r\nUna pizca de sal <br>\r\n1/2 cucharadita de jengibre molido <br>\r\n1 huevo', 'Machacamos en un mortero los ajos, la pimienta, la sal y el perejil. <br>\r\nAñadimos este majado a la carne picada junto con el pan que hemos mojado con la leche, el jengibre y el huevo. <br>\r\nMezclamos todo muy bien. Formamos pequeñas bolitas que pasamos ligeramente por harina y freímos en aceite de oliva virgen extra bien caliente. <br>\r\nUna vez que estén fritas las sacamos y dejamos sobre papel de cocina. Reservamos. <br>\r\nEn una cazuela pochamos las zanahorias y los puerros, cuando comiencen a dorarse incorporamos el tomate sin piel y cortado en trozos, lo pochamos también, añadimos el agua y el vino junto con una pizca de sal. <br>\r\nUna vez que haya hervido batimos bien la salsa con una batidora eléctrica (si la queremos más fina la pasamos por el chino). <br>\r\nIntroducimos las albóndigas y dejamos que se cocinen en la salsa unos diez o quince minutos. Servimos.'),
('Cordero miel y mostaza', '6 chuletas de cordero <br>\r\n2 patatas <br>\r\nMostaza en grano <br>\r\nMiel <br>\r\nSal al gusto <br>\r\nPimienta al gusto <br>\r\n1 chorro de aceite de oliva <br>\r\n2 dientes de ajo <br>', 'Pelar, limpiar y cortar las patatas por la mitad y en rodajas. <br>\r\n\r\nFreír las patatas en una sartén con abundante aceite caliente.<br>\r\n\r\nFreir las chuletas con unos ajitos pelados enteros y cuando esten medio hechos, quitar los ajos y ponerla mostaza en grano y la miel al gusto. <br>\r\n\r\nMontamos el plato de chuletas de cordero con salsa de miel y mostaza como queramos. '),
('Pollo con almendras', '2 pechugas de pollo cortadas en dados <br>\r\n1 zanahoria <br>\r\n1 cebolla <br>\r\n150g almendras crudas <br>\r\n200g caldo de pollo <br>\r\n100g salsa de soja <br>\r\n1 cucharadita de azúcar <br>\r\n3 cucharadas de agua <br>\r\nMaizena', 'Cortamos las pechugas en dados y las disponemos en un tupper. Cubrimos con salsa de soja y una cucharadita de azúcar. Tapamos el tupper y llevamos a la nevera durante 3 horas. <br>\r\nUna vez falten 15  minutos para que transcurra el tiempo de maceración, tostamos las almendras en una cazuela con un poquito de aceite, reservamos. <br>\r\nPelamos la zanahoria y la cebolla, cortamos en trozos pequeños y salteamos en una sartén con unas gotas de aceite de oliva virgen extra, reservamos. <br>\r\nRetiramos parte de la salsa de soja y freímos el pollo, añadimos las verduras y las almendras, cubrimos todo con caldo de pollo y dejamos cocinar durante 15 minutos. <br>\r\nEn un vaso ponemos 2 cucharaditas de Maizena y agua. Mezclamos bien y vertemos en la cazuela, dejamos cocinar durante 10 minutos hasta que la salsa espese. <br>\r\nServimos muy caliente.'),
('Estofado', '500 gramos de ternera para guisar <br>\r\n1 cebolla <br>\r\n2 zanahorias <br>\r\n4 patatas <br>\r\n100 gramos de tomate frito <br>\r\n1 hoja de laurel <br>\r\n100 mililitros de vino blanco <br>\r\n2 cucharadas soperas de harina <br>\r\n1 chorro de aceite de oliva <br>\r\n1 pizca de sal <br>\r\n1 pizca de pimienta', 'Corta la carne en tacos, aunque ya en la carnicería puedes pedirla preparada para guisar. Condimenta con un poco de sal y pimienta. Reboza los trozos en un poco de harina. <br>\r\nPon una cazuela con un buen chorro de aceite a fuego fuerte, añade la carne y dórala. <br>\r\nCuando empiece a dorarse, puedes sacarla de la cazuela o dejarla para agregarla luego. Corta la cebolla en trozos pequeños y añádela junto a la carne. Deja pochar la cebolla junto con la carne. <br>\r\nCuando ya esté casi pochada, añade el tomate frito. Remueve todo junto y deja cocinar unos minutos. <br>\r\nAñade el vino blanco y deja evaporar. <br>\r\nAñade las zanahorias cortadas en rodajas, la hoja de laurel y un vaso grande de agua. Deja cocinar 30 minutos. <br>\r\nPela y corta las patatas, cubre con más agua si hace falta. Deja cocinar carne de ternera guisada unos 20-30 minutos más. <br>\r\nCuando estén listas las patatas y la carne, prueba de sal y déjalas en su punto. ¡Tu estofado de carne con patatas estará listo para comer!'),
('Solomillo a la pimienta', '1 solomillo de cerdo cortado en medallones <br>\r\n70 ml. de brandy <br>\r\n200 ml. de nata para cocinar o crema de leche <br>\r\n1 y media cucharadas de pimienta en granos <br>\r\nmedia pastilla de caldo de carne <br>\r\nSal y pimienta al gusto <br>\r\nAceite de oliva <br>', 'Comenzamos la elaboración de nuestro solomillo de cerdo a la pimienta, para ello, en una sartén a temperatura media y con un poco de aceite de oliva, agregamos nuestros medallones de solomillo de cerdo salpimentados y cocinamos entre 3 y 4 minutos por cada lado. <br>\r\nEn la misma sartén donde cocinamos nuestro solomillo de cerdo, agregamos el brandy y removemos (dejamos cocinar por 2 minutos para que se evapore todo el alcohol) luego agregamos los granos de pimienta y cocinamos por 1 minuto, luego agregamos la nata o crema de leche, la pastilla de caldo de carne, removemos y dejamos cocinar por 3 minutos. <br>\r\nColocamos nuestro solomillo de cerdo en un plato, agregamos la salsa de pimienta por encima y ya tenemos listo nuestro riquísimo solomillo a la pimienta.¡¡ que aproveche!!'),
('Conejo en salsa española', '1 conejo <br>\r\n4 dientes de ajo <br>\r\n1 pizca de sal <br>\r\n1 pizca de pimienta negra molida <br>\r\n1 chorro de vinagre <br>\r\n1 manojo de romero <br>\r\n1 manojo de tomillo <br>\r\nmedia cucharadita de pimentón dulce <br>\r\n1 chorro de aceite de oliva <br>\r\n1 chorro de agua <br>\r\n1 rebanada de pan', 'Fríe el conejo troceado y los ajos pelados en una sartén con 3 cucharadas de aceite de oliva. Salpimienta y reserva. <br>\r\nEn la misma sartén, fríe 3 rebanadas de pan sin retirar los ajos. Añade más aceite si es necesario. <br>\r\nPara continuar con esta receta de conejo en salsa fácil, tritura el pan frito con un par de ajos, el pimentón, un chorrito de vinagre y un vaso de agua. Esto es lo que permitirá obtener una salsa espesa. <br>\r\nVuelve a poner el conejo en la sartén, agrega las hierbas aromáticas y la salsa de pan y ajo. Deja cocer el conejo en salsa durante 15 minutos a fuego medio. Si quieres, puedes añadir algunas verduras, como zanahoria rallada, cebolla y/o pimiento picado, ya que la salsa española también se puede elaborar con estos ingredientes.'),
('Costillas a la parrilla', '6 costillas de cerdo (1 kg, aprox.) <br>\r\n2 cucharadas de paprika (30 g) <br>\r\n1 cucharada de pimienta molida (15 g) <br>\r\n1 cucharada de comino en polvo (15 g) <br>\r\n5 dientes de ajo sin piel (45 g) <br>\r\n1 cucharada de orégano seco (15 g) <br>\r\n1 vaso de agua tibia (200 ml) <br>\r\n3 cucharadas de aceite de oliva (45 ml) <br>\r\n2 cucharadas de vinagre de vino tinto (30 ml)\r\n', 'Lo primero que harás es preparar el condimento para las costillas. Para poder hacerlo necesitarás mezclar todas las especias en un vaso de agua tibia. <br>\r\nLuego, deberás emplear una brocha para untar y cubrir generosamente la totalidad de las costillas con las especias. <br>\r\nAsegúrate de cubrir los espacios entre las uniones de la carne y el hueso. Déjalo reposar durante al menos 15 minutos. Reserva. <br>\r\nSi tienes un medidor de temperatura, empléalo y fija el calor de la parrilla en 165 ºC. <br>\r\nUna vez tengas la temperatura deseada, coloca las costillas y cierra la tapa de la parrilla. Dejarás asar por 20 minutos. <br>\r\nPara finalizar, una vez abierta la tapa, deberías ver el hueso de las costillas bien ahumado y la carne jugosa y enrojecida. Será indicador de que están listas.'),
('Revuelto de morcilla', '1 morcilla <br>\r\n1 cebolla mediana <br>\r\n1 diente de ajo <br>\r\nUvas pasas al gusto <br>\r\n1 guindilla cayena y pimienta negra <br>\r\nSal <br>\r\nAceite de oliva virgen extra <br>\r\n3 huevos frescos\r\n', 'Se pica muy fino la cebolla y el ajo. <br>\r\nUna vez picados se ponen en un sartén para que se doren, se aconseja que  la sartén sea amplia, se añade un poco de aceite de oliva y sal. Para pochar la cebolla, el aceite debe estar muy caliente, luego ya lo puedes bajar, sin prisas se hace mejor. <br>\r\nDespués se Abre la morcilla y se saca la mezcla de arroz, cebolla, grasa y sangre del cerdo. Si queremos que tenga un puntito picante, podemos añadir dos pequeñas guindillas cayena. <br>\r\nSe Añade la morcilla, las uvas, los piñones y las especias a la cebolla y el ajo, cuando estén bien pochados. Removemos para homogeneizar bien todos los ingredientes y se deja a fuego bajo para que se junten los sabores. <br>\r\nEn un cuenco aparte, batimos los huevos. Se puede añadir alguna especia si se quiere. <br>\r\nCuando la morcilla se ha mezclado bien se añade el huevo batido y dejarlo cuajar solo parcialmente.'),
('Sándwich de Frankfurt', '4 rebanadas pan de molde <br>\r\n4 quesitos <br>\r\n4 Frankfurt <br>\r\n4 lonchas jamón serrano <br>\r\nCebolla frita <br>\r\nQueso para fundir', 'Ponemos el horno a precalentar 10min a 200° <br>\r\nEstendemos los quesitos en el pan de molde 1/1\r\nPonemos las rebanadas estiradas de dos en dos. <br>\r\nCortamos los Frankfurt a la mitad y los ponemos sobre el pan, añadimos una capa de jamon, una capa de cebolla y lo tapamos por completo con el queso de fundir. <br>\r\nSobre la bandeja del horno o sobre papel de horno ponemos los sándwich y los ponemos 5min a calentar,\r\nPasado ese tiempo ponemos a gratinar otos 5min. Y listo.'),
('Pulled pork', '6 cucharadas de ketchup. <br>\r\n4 cucharadas de azúcar mascabo. <br>\r\n4 cucharadas de vinagre de manzana. <br>\r\n6 cucharadas de caldo en el que se cocinó la bondiola.', 'Masajear por todos lados la bondiola con la pasta para marinar, asegurándose de que quede bien embadurnada. Envolver esto en una bolsa o papel film y dejar marinando en la heladera, todo el tiempo que se pueda. <br>\r\nDisolver un caldo de verduras en 2 tazas de agua hirviendo. Agregar el jugo de 1 naranja. <br>\r\nEn una olla colocar la bondiola marinada junto al caldo con naranja más una pizca de sal y cocinar por el tiempo que sea necesario. <br>\r\nEn una fuente grande colocar la carne ya cocida y desmecharla con dos tenedores. <br>\r\nEn un bol poner 6 cdas. de ketchup, 4 cdas. de vinagre de manzana, 4 cdas. de azúcar, 1 pizca de sal, 6 cdas. del jugo que quedó del horneado y mezclar todo muy muy bien. Agregar esta salsa a la carne. <br>\r\nCortar un pan de Viena a la mitad y armar un sandwich con verduras y la carne.'),
('Filetes de pavo a la naranja', 'filetes de pavo <br>\r\nuna cucharada de mantequilla <br>\r\nsal <br>\r\npimienta\r\nel zumo de dos naranjas <br>\r\npizca de canela (opcional) <br>\r\n1/2 vaso de caldo de pollo', 'Salpimentamos los filetes. En una sartén al fuego fundimos la mantequilla, y doramos en ella los filetes. <br>\r\nUna vez dorados, añadimos el medio vaso de caldo, ésto nos ayudará a desglasar y recojer los jugos que ha dejado la carne y darán sabor y color a la salsa. <br>\r\nEchamos el zumo de naranja. <br>\r\nPodemos poner tambien unos gajos de naranja que nos servirán luego para la decoración. <br>\r\nDejamos reducir un poco la salsa, echamos la pizca de canela, y servimos, decorado con los gajos de naranja.'),
('Sesos rebozados', '1 sesada de ternera, o bien dos de cordero <br>\r\nAgua <br>\r\nSal <br>\r\n1 hoja de laurel <br>\r\n1 cucharada sopera de vinagre <br>\r\n100 gramos de harina <br>\r\n3 huevos <br>\r\n1/4 de aceite de oliva <br>\r\nlimón', 'Limpiamos los sesos y les damos un ligero hervor en agua, que los cubra, con la hoja de laurel, el vinagre y sal. Sólo se cocerán de 3 a 5 minutos. <br>\r\nEscurridos y casi fríos los cortamos en dados que pasamos por la harina y los huevos batidos y freímos en el aceite de oliva La Espańola, puesto al fuego en una sartén, y muy caliente. Se hacen doraditos por ambos lados y precisan muy poco tiempo. <br>\r\nPara darle un toque final a los sesos rebozados los servimos acompańados del limón cortado a trozos.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pescado`
--

CREATE TABLE `pescado` (
  `Nombre` varchar(30) NOT NULL,
  `Ingredientes` text NOT NULL,
  `Descripcion` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `pescado`
--

INSERT INTO `pescado` (`Nombre`, `Ingredientes`, `Descripcion`) VALUES
('Merluza a la plancha', '2 filetes de merluza (500 g).<br>\r\n4 dientes de ajo sin piel (50 g).<br>\r\n2 ramas de perejil fresco (20 g).<br>\r\n1 cucharada de pimienta negra molida (25 g).<br>\r\n1/2 taza de aceite de oliva extra virgen (40 mL).', 'Primero, prepara el aliño. En un vaso con aceite de oliva extra virgen introduce los dientes de ajo finamente cortados junto a las ramas de perejil troceadas de igual manera.<br>\r\nConserva por 1 hora.<br>\r\nLuego, prepara los filetes de merluza. Lávalos para remover restos indeseados y aplica la pimienta en ambos lados.\r\nColoca la plancha a fuego medio con un chorrito de aceite.<br>\r\nFinalmente, vierte el contenido con aceite de oliva y aliños en los filetes y llévalos a la plancha hasta que cuezan por ambas caras. Sirve y disfruten.'),
('Atún al ajillo', '1 cabeza de ajo (45 g).<br>\r\n2 tazas de vinagre (220 mL).<br>\r\n2 rodajas de atún fresco (425 g).<br>\r\n1 cucharada de pimienta negra molida (25 g).<br>\r\n1 cucharada de aceite de oliva extra virgen (30 mL).<br>\r\n2 cucharadas de comino en polvo (50 g).', 'Primero, lava muy bien las rodajas de atún y escurre el exceso de agua.<br>\r\nLuego, con la ayuda de una olla de tamaño considerable, introduce las rodajas con las tazas de vinagre, un poco de sal y déjalo cocer a fuego alto por 10 minutos.<br>\r\nMientras, machaca muy bien los dientes de ajo junto con el comino en polvo y un chorrito de aceite. Lo ideal es que te quede una mezcla homogénea.<br>\r\nUna vez listas las rodajas en el agua, procede a retirarlas y espera a que enfríen un poco.<br>\r\nLuego, úntalas con la preparación del ajo, comino y aceite y asegúrate que cubra bien la superficie del pescado.<br>\r\nDeja que todo adquiera sabor durante 25 minutos.<br>\r\nSi lo deseas, puedes comerlo de una vez. Otra opción es refrigerar y pasar por la plancha al día siguiente.'),
('Salmón a la plancha', '1 limón (20 g).<br>\r\n1 rodaja grande salmón (300 g).<br>\r\n2 dientes de ajo sin piel (15 g).<br>\r\n1 cucharada de sal marina (25 g).<br>\r\n1/2 taza con hierbas provenzales (50 g).<br>\r\n2 cucharadas de perejil molido (50 g).<br>\r\n1 cucharada de aceite de oliva extra virgen (30 mL).', 'Primero, lava bien la rodaja de salmón con abundante agua.<br>\r\nLuego, escurre y lleva el filete a una tabla donde sazonarás.<br>\r\nEntonces, usa los dientes de ajo previamente troceados con la sal, perejil molido y las hierbas provenzales.<br>\r\nLuego, envuelve la rodaja de salmón en papel aluminio o papel “film” para guardar en el refrigerador por 2 horas.<br>\r\nFinalmente, retira del refrigerador, espera a que descongele y lleva a la plancha con un chorrito de aceite de oliva extra virgen. Cuece por ambas caras y disfruta.'),
('Calamares a la romana', '4 calamares medianos<br>\r\n2 huevos<br>\r\n300 gramos de harina de trigo<br>\r\nLevadura química (polvos de horneado)<br>\r\n300 ml de agua<br>\r\nSal<br>\r\nAceite de girasol y Aceite de oliva', 'El primer paso de esta receta de calamares a la romana es comprar el producto fresco y limpio. Puedes adquirirlos ya cortados o en piezas enteras. Para limpiar los calamares enteros, retira los tentáculos con delicadeza para no romper o dañar la bolsa de tinta que contiene a continuación de la cabeza.<br>\r\nQuita la piel del calamar, es decir, una lámina transparente similar a un trozo de plástico. También debes extraer la boca, situada en el centro de la base de los tentáculos.<br>\r\nCon el interior de los calamares lavado, pasa a secarlos con papel absorbente y les vuelves a dar la vuelta para cortarlos en aros: deben ser de un centímetro de ancho aproximadamente. Si son calamares con aletas muy grandes, puedes cortarlas también por la mitad.<br>\r\nUna vez tengas listos los aros de los calamares, rompe los huevos y ponlos en un cuenco para batirlos con un batidor o un tenedor para hacerlo a mano. Después, vierte el agua en el mismo cuenco y continúa batiendo para lograr que se mezcle bien con los huevos.<br>\r\nAñade levadura química y un poco de sal al cuenco para continuar batiendo. Seguidamente, agrega la harina de trigo poco a poco sin parar de remover con la varilla para conseguir que la harina se incorpore al resto de la mezcla homogéneamente.<br>\r\nTras incorporar la harina de trigo al completo, vierte un poco de aceite de oliva en el cuenco y lo mezclas con el resto de ingredientes para que quede bien incorporado.<br>\r\nEn una sartén, echa aceite de girasol abundante y lo pones a calentar para freír los calamares. \r\n'),
('Dorada', '2 doradas de ración limpias y abiertas. <br> \r\n1 cebolla morada<br>\r\n1 diente de ajo<br> \r\n2-3 tomates<br> \r\n1 cucharada de alcaparras<br>\r\n2 filetes de anchoas<br> \r\n1 cucharada de aceitunas negras sin hueso<br>\r\n1/2 limón<br>\r\n1 vaso de vino blanco<br>\r\nEspecies: orégano, perejil, sal, pimienta negra<br>\r\naceite de oliva virgen extra.', 'Precalentar el horno a 200ºC y engrasar una fuente de horno con aceite. Cortar la cebolla en juliana fina y disponer en el fondo de la fuente. Picar el diente de ajo con las anchoas y agregarlos. Cortar los tomates en rodajas gruesas y colocarlos también sobre la cebolla. Salpimentar y agregar un poco de orégano. Hornear durante 10-15 minutos, hasta que la cebolla empiece a estar tierna.<br>\r\nSalpimentar las doradas y colocarlas encima de las verduras. Regar con el zumo de limón, el vino blanco y repartir por encima las alcaparras y aceitunas cortadas en rodajas. Hornear unos 10 minutos más y servir con orégano y perejil.'),
('Gambas al ajillo', '250 g de gambas frescas<br>\r\n8 dientes de ajo<br>\r\n2 guindillas (pimiento picante, chile)<br>\r\nUna pizca de sal<br>\r\nAceite de oliva virgen extra', 'Freimos los ajos y las guindillas.<br>\r\nPelamos las gambas y reservamos.<br>\r\nPelamos los ajos y cortamos en rodajas.<br>\r\nEn una sartén ponemos bastante aceite de oliva virgen extra, los ajos y las guindillas, dejamos que se cocinen a fuego medio. Es conveniente que el fuego esté suave ya que así daremos tiempo a que el aceite coja el sabor de las guindillas.<br>\r\nIncorporamos las gambas\r\nJusto cuando los ajos comiencen a dorarse incorporamos las gambas y apagamos el fuego.\r\nCon el calor residual las gambas estarán hechas, no debemos dejar que se cocinen en exceso ya que corremos el riesgo de que se queden algo secas.\r\nServimos enseguida, lo tradicional es hacerlo sobre una cazuelita de barro.\r\n'),
('Sardinas', 'Sardinas de un tamaño (mediano grande), 1 Kilo <br>\r\nAjo picado muy pequeño <br>\r\nAceite de Oliva Virgen <br>\r\nPerejil picado muy pequeño <br>\r\nVinagre ', 'En unas brasas se ponen en la parrila y cuando esten, se colocaran en una fuente honda por capas, en cada capa se le pondrá mucho ajo y perejil mezclado, después un chorreón de Vinagre, y luego un buen chorreón de Aceite.<br>\r\nAsí en cada capa de sardinas. Entre parrillada y parrillada, las taparemos con un trapo limpio, y sobre el trapo pondremos un periodico o carton, nunca tapadera de metal o cristal, y menos plastico.<br>\r\nCuando esten las ultimas sardinas puestas y adobadas, lo dejaremos reposar unos 5 o 10 minutos.'),
('Gambas rebozadas', '800 gramos de gambas o langostinos pelados <br>\r\n2 huevos <br>\r\n200 gramos de pan rallado <br>\r\nSalsa agridulce <br>\r\nAceite de oliva <br>\r\nSal <br>\r\n1 ramita de perejil <br>', 'Seca las gambas o langostinos suavemente con papel absorbente. Pon a calentar una sartén honda con abundante aceite hasta que alcance unos 160º.<br>\r\nReboza las gambas: Bate los huevos ligeramente en un plato hondo. Vierte el pan rallado o el preparado para rebozar en un plato. Pasa las gambas por el huevo, deja escurrir el exceso y, a continuación, rebózalas en el pan presionando suavemente.<br>\r\nFríe las gambas por tandas, dejando que se hagan bien por dentro y por fuera; cuando estén doradas, retíralas con una espumadera y déjalas que escurran el exceso de aceite sobre un plato forrado con papel absorbente.<br>\r\nSírvelas enseguida, para que no se enfríen, espolvoreadas con unas hojitas de perejil lavado picado y acompañadas de la salsa agridulce dispuesta en un cuenco o salsera.\r\n'),
('Mejillones a la marinera', '1 Kg de Mejillón de Galicia <br>\r\n1 cebolla mediana <br>\r\n2 cucharadas de harina de trigo  <br>\r\n3 cucharadas de tomate frito (casero) <br>\r\n1/2 vaso de vino blanco <br>\r\n1/2 vaso del agua de cocción <br>\r\nPimentón de la Vera, dulce o picante <br>\r\n1 hoja de laurel <br>\r\nAceite de oliva virgen extra <br>\r\nSal', 'Lavamos los mejillones debajo del grifo, quitándole las barbas y la suciedad o impurezas que puedan traer adheridas. En una cazuela, disponemos los mejillones, con un fondo de agua y una hoja de laurel. Cocinamos a fuego alto, hasta que abran sus conchas. Reservamos. <br>\r\nPicamos la cebolla en “brunoise” (dados pequeños) y sofreímos en una sartén con aceite virgen extra. Salamos al gusto. Cuando esté blandita, añadimos la harina, removemos y cocinamos a fuego medio. <br>\r\nVertemos el vino y 1/2 vaso del agua de cocción de los mejillones, colándola previamente. Añadimos el tomate frito y 1 cucharada de postre de pimentón de la Vera. Puede ser dulce o picante, según vuestro gusto. <br>\r\nMezclamos todo bien y dejamos cocinar unos 10/12 minutos a fuego medio-bajo, para que vaya espesando la salsa. Probamos, y rectificamos de sal si es necesario. <br>\r\nEn una cazuela plana (o de barro), incorporamos  los mejillones, añadimos la salsa y dejamos cocinar todo junto 2/3 minutos, a fuego medio. De esta manera los mejillones se empaparán del sabor intenso de nuestra Salsa Marinera.'),
('Almejas', '600 g de almejas <br>\r\n4 o 5 dientes de ajo <br>\r\n1 punta de guindilla o pimienta de Cayena <br>\r\nSal y perejil fresco picado <br>\r\nVino blanco seco al gusto <br>\r\nAceite de oliva virgen extra', 'Lavamos muy bien las almejas en varias aguas y, si es posible, las ponemos una hora en agua con sal o las rociamos con sal gruesa y a la media hora las lavamos con agua. De esta forma perderán la arena interior si la tienen.<br>\r\nEn una sartén ponemos un fondo de aceite y salteamos unos minutos el ajo laminado. Cuando el ajo empiece a tomar color ponemos la guindilla y al momento las almejas y el medio vasito de vino. Hay que subir el fuego en ese momento para que el vino se evapore con rapidez mientras se van abriendo las almejas.<br>\r\nMientras se van abriendo las almejas espolvoreamos con el perejil picado muy finito y damos unas vueltas para que se integre bien en la salsa.<br>\r\nLa mayoría de las veces no es necesario añadir ni sal a las almejas al ajillo. Siempre recomendamos no sazonar demasiado los platos marineros y respetar su sabor, pero si quieres poner algo de sal ahora es el momento de añadirla.<br>\r\nCuando vemos que las almejas se han abierto retiramos del fuego y servimos al momento.'),
('Langosta', '2 ud de Langosta vivas (800 gramos cada una) <br>\r\n40 g de Mantequilla <br>\r\n20 ml de Aceite de oliva virgen <br>\r\n2 cs de Perejil fresco picado <br>\r\n1 ud de Zumo de limón <br>\r\nSal\r\n', 'Cocemos las langostas partiendo de agua fría durante 5 minutos.<br>\r\nRetiramos del fuego, las colocamos apoyadas sobre su parte plana y hacemos un corte longitudinal de la cabeza a la cola y para dividir cada una en dos mitades.<br>\r\nCalentamos la mantequilla con el aceite en un cazo a fuego lento hasta que se derrita.<br>\r\nPincelamos con la mitad del contenido del cazo la parte de la carne de cada langosta, rociamos con el zumo de limón y espolvoreamos con el perejil picado y una pizca de sal. <br>\r\nLas colocamos en la parrilla sobre las brasas con el lado abierto hacia abajo durante 4 minutos. <br>\r\nDamos la vuelta y las ponemos con el lado abierto hacia arriba durante 2 minutos más.'),
('Merluza con salsa', '1 cebolla\r\n4 dientes de ajo\r\n400 g lomos de merluza\r\n300 g salsa de tomate casera\r\nPimienta recién molida\r\nSal\r\nAceite de oliva virgen extra\r\nPerejil fresco o seco\r\n', 'Empezaremos preparando todos los ingredientes y, para ello, en primer lugar pelamos la cebolla y la picamos finamente. <br>\r\nPelamos también los dientes de ajo y los laminamos. <br>\r\nA continuación sazonamos la merluza al gusto con una pizca de sal y pimienta. En esta ocasión yo estoy usando lomos de merluza, pero podrás usar filetes o rodajas si lo prefieres. <br>\r\nCalentamos una cacerola baja con un buen chorro de aceite de oliva y colocamos los ajos y la merluza. En este momento sellaremos la merluza por ambos lados y la retiraremos del fuego, pues la acabaremos de cocinar en la salsa. <br>\r\nDejamos los ajos en la sartén y agregamos la cebolla picada. <br>\r\nLa sazonamos al gusto con una pizca de sal y agregamos un chorrito más de aceite de oliva si es necesario. <br>\r\nRemoveremos muy bien, despegando con una espátula de madera los posibles restos de pescado que se nos hayan pegado al fondo de la sartén. <br>\r\nPocharemos la cebolla unos 5 minutos o hasta que se haya ablandado y esté tierna, removiendo de vez en cuando. <br>\r\nEn este momento agregamos la salsa de tomate, preferiblemente casera, y mezclamos bien. <br>\r\nCuando la salsa esté caliente y empiece a burbujear, agregamos la merluza y espolvoreamos con perejil fresco o seco por encima.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `verdura`
--

CREATE TABLE `verdura` (
  `Nombre` varchar(45) NOT NULL,
  `Ingredientes` text NOT NULL,
  `Descripcion` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `verdura`
--

INSERT INTO `verdura` (`Nombre`, `Ingredientes`, `Descripcion`) VALUES
('Revuelto de espinacas', '2 ajos <br>\r\n2 huevos <br>\r\n120 g de espinacas <br>\r\nsal <br>\r\naceite de oliva', 'Primero, lava las espinacas y cortalas en tiras. Pela los dientes de ajo. <br>\r\nLuego, en una sartén, vierta el aceite y cuando esté caliente un poco, sofríe los dientes de ajo hasta que comience a dorarse. añada entonces las espinacas y mantenlas a fuego medio durante 5-6 minutos. Aprovecha mientras para batir los huevos. <br>\r\nAgrega los huevos batidos y un poquito de sal, y cocina a fuego bajo hasta que el huevo esté en el punto de cocción que te agrada. <br>\r\nSírvetelo caliente y disfrútalo con unas tostaditas.'),
('Lasaña de verduras', '1 Pimiento verde <br>	\r\n1 Pimiento rojo	 <br>		\r\n1 Calabacín  <br>		\r\n100 g Champiñones <br>			\r\n180 g Zanahorias <br>			\r\nAceite de oliva Virgen Extra <br>		\r\n150 g Salsa de tomate y albahaca <br>			\r\nSal <br>			\r\nPimienta <br>			\r\n500 ml	Bechamel <br>			\r\nQueso parmesano	 <br>		\r\nOrégano	y Albahaca fresca', 'Cortamos los pimientos, el calabacín y los champiñones en dados, rallamos las zanahorias y salteamos en una sartén con aceite de oliva. Añadimos salsa de tomate y salpimentamos. <br>\r\nPincelamos la base de un molde de horno con aceite de oliva, disponemos unas láminas de lasaña y extendemos sobre ellas las verduras salteadas. <br>\r\nCompletamos con una capa de bechamel, espolvoreamos el queso y repetimos el proceso hasta llegar a la última capa que quedará cubierta con más bechamel que las anteriores. <br>\r\nVolvemos a espolvorear queso rallado, horneamos durante 30 minutos a 180 ºC, decoramos con orégano, albahaca fresca y… ¡ya podemos disfrutar de este riquísimo plato!'),
('Crema de calabaza', '750 g de calabaza (ya limpia) <br>\r\n1 patata <br>\r\n1 cebolla <br>\r\n4 quesitos desnatados <br>\r\n1 pizca de sal <br>\r\nPimienta negra', 'Pelamos la cebolla y cortamos en Juliana. Pelamos la patata y cortamos en trozos. A la calabaza le quitamos la piel y la parte del centro con hebras y semillas y la cortamos en cubos pequeños. Ponemos en una olla dos o tres cucharadas de aceite de oliva virgen extra y pochamos a fuego suave la cebolla. Cuando comience a dorarse, añadimos la calabaza y la patata, rehogamos un par de minutos y añadimos el agua. Dejamos cocer unos 20 minutos. <br>\r\nPasado este tiempo, incorporamos los quesitos y trituramos muy bien con la batidora. Y ya tenemos lista para servir esta deliciosa Crema de calabaza.'),
('Brochetas de verduras', '1 cebolla morada <br>\r\n1 calabacín <br>\r\n1 pimiento amarillo <br>\r\n16 champiñones, descarta el tallo o pie <br>\r\n16 tomates cherry <br>\r\nAceite de oliva virgen extra al gusto (opcional) <br>\r\nSal al gusto <br>\r\nPimienta negra molida al gusto <br>\r\nCebollino picado para decorar (opcional)', 'Lava y trocea las verduras, lo ideal es que los trozos sean más o menos del mismo tamaño para que se hagan todas las verduras por igual. La cantidad es orientativa, ya que puede variar en función del tamaño que tengan las verduras y de cómo las cortes. <br>\r\nPara montar las brochetas, pincha las verduras en el orden que quieras. Nosotros las pusimos en este orden: cebolla morada, champiñón, calabacín, tomate cherry y pimiento amarillo y pusimos dos de cada por brocheta. <br>\r\nCocina las verduras en un grill, parrilla o sartén con un poquito de aceite de oliva virgen extra (opcional) durante unos 10 ó 15 minutos por cada lado o hasta que se doren. Retira del fuego, añade sal y pimienta al gusto, decora con un poco de cebollino picado (opcional) y sirve inmediatamente. <br>\r\nLas brochetas están mejor recién hechas. Puedes prepararlas y guardarlas sin cocinar en la nevera en un recipiente hermético durante unos 3 ó 4 días o ya cocinadas, también en un recipiente hermético en la nevera durante unos 2 ó 3 días.'),
(' Medallones de verduras', 'Un calabacín mediano <br>\r\n1 zanahoria mediana <br>\r\n2 huevos <br>\r\nOpcional: Un par de golpes de especias aromáticas al gusto <br>\r\n2 cucharadas soperas rasas de harina <br>\r\nSal y pimienta al gusto <br>\r\nQueso rulo de cabra o cualquier queso <br>\r\nAceite de oliva virgen extra', 'Rallamos con un rallador grueso la zanahoria pelada y el calabacín. Es mejor que dejes la piel del calabacín si está firme y brillante. Una vez rallada la verdura la ponemos en un bol. <br>\r\nBatimos los huevos y los añadimos al bol de la verdura. Salpimentamos y ponemos las especias que vayamos a utilizar y la harina. Mezclamos todo muy bien hasta que quede perfectamente integrado. <br>\r\nAhora vamos a ir poniendo porciones de esa mezcla de verduras en una sartén antiadherente bien aceitada. Ponemos una cucharada de verduras, colocamos una rodaja de queso encima y cubrimos con más verdura, prensando con una cuchara y dando forma redonda. <br>\r\nSi quieres te puedes ayudar de una aro de emplatar para que tengan una presentación más vistosa y los medallones de verdura resulten más gruesos. <br>\r\nHay que hacer los medallones de verdura a fuego muy lento para que se hagan bien por dentro y la verdura no quede cruda. Cuando estén dorados le damos la vuelta u dejamos que se hagan del otro lado. <br>\r\nLos medallones de verdura se sirven calientes, recién hechos, con el queso fundido en su interior. Se pueden acompañar con una salsa de tomate para pizza o una mayonesa aromatizada al curry.'),
('Sopa de verduras', '1 Puerro <br>\r\n2 Zanahorias <br>\r\n150 g Repollo <br>\r\nApio rama <br>\r\n1 Nabo <br>\r\nAceite de oliva virgen extra <br>\r\nSal <br>\r\nPimienta negra molida <br>\r\nCaldo de verduras casero 1.5 l', 'Lavamos todas las verduras y pelamos las que sea necesario. En nuestro caso las zanahorias, el nabo y el puerro, al que retiramos la capa exterior. Cortamos todas ellas en juliana, es decir, en tiras finas y largas. <br>\r\nCalentamos el aceite en una cacerola amplia y rehogamos las verduras, todas juntas, durante unos diez minutos. A continuación añadimos el caldo de verduras casero y cocemos 15 minutos, lo suficiente para que las verduras queden al dente. <br>\r\nSi os gustan las verduras muy tiernas, las dejáis unos minutos más. En cualquier caso, una vez finalizada la cocción probamos el punto de sal y pimienta y ajustamos al gusto. Servimos la sopa bien caliente decorando cada plato con unas hojitas de perejil (opcional).'),
('Ensalada variada', '1 lechuga iceberg <br>\r\nmedio pimiento asado <br>\r\n4 o 5 tomatitos cherry <br>\r\nmedia cebolla fresca <br>\r\n1 huevo cocido <br>\r\n1 lata de atún natural <br>\r\nZanahoria rallada <br>\r\nCilantro <br>\r\nSal fina <br>\r\nAceite de oliva <br>\r\nZumo de un limón', 'Una vez hayamos cocido el huevo, sacado el agua de la lata de atún, y cortado medio pimiento asado previamente, escogemos un bol mediano-grande para ir añadiendo uno a uno todos los ingredientes que hemos seleccionado para nuestra ensalada variada. <br>\r\nLo primero será enjuagar la lechuga iceberg, que partiremos en 4 trozos iguales, seleccionando 3 de esos trozos. Los cortamos y añadimos al bol. A continuación iremos echando ingredientes sobre la marcha: media cebolla fresca a pequeñas tiras, un poco de zanahoria rallada, el atún natural desmenuzado, el huevo cocido a pequeños trocitos, los tomatitos cherry y por último, la mitad de un pimiento rojo asado. <br>\r\nEl último paso será añadir un poco de cilantro cortado y aliñar nuestra ensalada. Yo para este caso he hecho una mezcla de aceite de oliva (2 cucharadas soperas), un poco de sal fina y el zumo de un limón (pequeño). Mezclo este aliño previamente para no excederme en las cantidades, y cuando tengo una mezcla totalmente homogénea, la añado a la ensalada. <br>\r\n¡Ensalada variada lista para comer! ¿Quién dijo que a dieta no se podían comer cosas ricas?'),
('Tomates rellenos', '6 unidades de Tomates  <br>\r\n250 gramos de Atún en trozos al natural <br>\r\n150 gramos de Aceitunas negras (deshuesadas) <br>\r\n1 chorro de Aceite de oliva <br>\r\n1 rama de Perejil <br>\r\n1 pizca de Sal <br>\r\n1 pizca de Pimienta', 'En primer lugar lo que debemos hacer es lavar los tomates. Luego, con ayuda de un cuchillo bien afilado cortamos la parte superior de cada tomate y retiramos el corazón y las semillas usando una cucharita. La idea es dejar los tomates huecos para poder rellenarlos. <br>\r\nSeguidamente, vuelve a lavar los tomates y colócalos boca abajo sobre papel absorbente para que escurran. Déjalos en esta posición por una media hora, luego podrás salpimentar al gusto. <br>\r\nAparte, para preparar el relleno de los tomates, escurre el atún, las aceitunas y pica todo finamente. Conserva un par de aceitunas enteras para cortar en rodajas y utilizarlas en la decoración final del plato. <br>\r\nA continuación, mezcla estos dos ingredientes con el perejil, también finamente picado, y adereza con aceite de oliva, sal y pimienta. Si deseas también puedes incluir un poco de mayonesa en este paso. <br>\r\nFinalmente, rellena los tomates con el preparado de atún y conserva en la nevera hasta que llegue el momento de servir. No olvides decorar los tomates rellenos de atún con las rodajas de aceitunas.'),
('Escalivada de verduras', '2 berenjenas grandes <br>\r\n2 pimientos rojos grandes <br>\r\n3 cebollas pequeñas <br>\r\n5 tomates pequeños <br>\r\nAceite de oliva virgen extra <br>\r\n2 dientes de ajo <br>\r\nSal (al gusto de cada casa)', 'Pelamos las cebollas y las lavamos, junto con el resto de las verduras bajo el grifo, las secamos con papel de cocina. Las colocaremos directamente sobre una bandeja de horno. <br>\r\nCon el horno previamente caliente a 200º C, horneamos las verduras durante 1 hora. No es necesario que le añadamos ni aceite de oliva ni sal. <br>\r\nCuando las verduras están aún calientes, casi recién salidas del horno comenzamos a prepararlas. Pelamos los pimientos y los abrimos a la mitad para retirarles las semillas interiores, aprovechando antes el agua que tendrán en su interior. Vamos dejando los pimientos y su agua en un plato. <br>\r\nPelamos los tomates y aprovechando el jugo que irán soltando lo troceamos para un nuevo plato eliminando alguna parte dura que podamos encontrarnos. Pelamos las berenjenas y les retiramos las semillas interiores. Las reservamos junto con su propio jugo. Troceamos las cebollas y las reservamos. <br>\r\nElegimos la fuente o bandeja donde vayamos a montar el plato y distribuimos las verduras cortadas en tiras, en el caso de los pimientos y las berenjenas, y en trozos los tomates y las cebollas. Regamos con los jugos que tenemos reservados de las verduras. <br>\r\nPelamos y troceamos los dientes de ajo y los distribuimos por la superficie de las verduras en la bandeja. Finalmente regamos con un buen aceite de oliva virgen extra. <br>'),
('Salmorejo', '6 tomates de pera, pelados <br>\r\n1/2 ajo, retirar el germen interior <br>\r\n2 rebanadas grandes de pan con mucha miga, quitarle la corteza <br>\r\n1/2 taza de aceite de oliva o 3/4 como máximo <br>\r\n1 Cda. de vinagre de jerez <br>\r\n1/4 cdta. de sal', 'Poner el pan en una bandeja y cubrir con agua. Dejar a remojo en el frigorífico toda la noche o unas horas. <br>\r\nEmpezamos pelando los tomates, puedes darles un hervor para que la piel se quite más fácilmente. Córtalos en trozos y retira las pepitas y su líquido. <br>\r\nColoca en el vaso de la batidora los tomates. Pela el ajo y retira el germen verde de su interior. Trituramos unos segundos. <br>\r\nEscurre bien el pan que teníamos a remojo y añádelo a la batidora junto con la sal y el pimentón (este último opcional). Tritura hasta que no queden grumos. <br>\r\nPoco a poco, añade el aceite mientras sigues triturando para que el salmorejo emulsione y adquiera su particular textura sedosa. <br>\r\nSírvelo frío con un chorrito de aceite de oliva por encima, también puedes añadir huevo duro, picatostes o unos taquitos de jamón.'),
('Ensalada de quinoa', 'media taza de quinoa sin cocinar (100 g) <br>\r\nmedia taza de maíz (35 g) <br>\r\nmedia zanahoria (40 g) <br>\r\n12 tomates cherry <br>\r\n12 aceitunas negras <br>\r\n1 aguacate <br>\r\nAceite de oliva virgen extra', 'Lava bien la quinoa antes de cocinarla para eliminar las saponinas (una sustancia amarga que se utiliza para hacer jabón). <br>\r\nCocina la quinoa siguiendo las instrucciones de paquete. Déjala enfriar o échale agua fría. <br>\r\nEn un bol echa la quinoa y el resto de los ingredientes. Aliña con aceite de oliva virgen extra al gusto.'),
('Revuelto de esparragos', '1 manojo espárragos verdes <br>\r\n3-4 huevos <br>\r\n1 diente ajo <br>\r\n1 cebolla verde', 'Quitamos la parte dura de los espárragos y los hervimos durante 5 minutos. Que queden al dente. <br>\r\nParamos el hervor y los sacamos a la tabla de cortar y los cortamos en trocitos. <br>\r\nMientras los espárragos hervían, cortamos la cebolla en trocitos. Cuando sacamos los espárragos, la ponemos en la sartén con un chorrito de aceite que se vaya pochando. <br>\r\nAñadimos los espárragos a la sartén y una vez estén bien integrados con la cebolla, añadimos los huevos. A mi me gusta romper la yema una vez este ya medio cuajada la clara. <br>\r\nServimos y a disfrutar!!\r\n'),
('Medallones de verduras', '12 medallones merluza <br>\r\n250 gramos gambas peladas <br>\r\n2 cebollas grandes <br>\r\n100 ml vino blanco <br>\r\n250 ml caldo de pollo <br>\r\n100 ml agua <br>\r\nSal', 'Pelamos la cebolla y la cortamos en juliana <br>\r\nEn una sartén con aceite, ponemos la cebolla a pochar a fuego medio bajo. <br>\r\nCuando la cebolla esté pochada, añadimos los medallones de merluza y los cocinamos 1 o 2 minutos con la cebolla a fuego medio-alto.  <br>\r\nAñadimos el vino, removemos y al minuto añadimos el caldo de pescado.  <br>\r\nDejamos hervir a fuego medio-alto 5 o 6 minutos.  <br>\r\nPasado el tiempo probamos de sal y rectificamos si fuera necesario. <br>\r\nPodemos cocer unas patatas y añadirlas a rodajas de 1 centímetro 2 minutos antes de apartar.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
